# Generated by Django 4.0.4 on 2022-05-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Orderphone',
            field=models.CharField(default='', max_length=14),
        ),
    ]
